server:
  port: 8092
spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521/RGDB
    username: env_user
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        format_sql: true
  freemarker:
    allow-session-override:
  jwt:
    length_expire: 6000000
    length_expire_refresh: 30L*60*10000
  #----------- config file
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  #----------- redis config
#  redis:
#    host: "172.24.66.76"
#    port: 6380
#----------- eureka developer config
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka # discovery service loc

base_type:
  users: users

