server:
  servlet:
    context-path: /hub
spring:
  profiles:
    active: developer
  #    active: operation
  #    active: test

  application:
    name: authentication-service # current service name used for eureka registration

  devtools:
    add-properties: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


#---- eureka public config
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 20 # Notifying Eureka that the client is up or down or killed (second)
    leaseExpirationDurationInSeconds: 20 # Notifying Eureka that the client is up or down or killed (second)
    prefer-ip-address: true # registers the service ip rather than the server name
  client:
    register-with-eureka: true # register him self at eureka
    fetch-registry: true # pull down a local copy of the registries
#----------- allowed cors origin
cors:
  allowed-origins:
    - http://172.24.66.76:8086
    - http://172.24.66.76:8082
    - http://localhost:3000
    - http://localhost:3001
