server:
  servlet:
    context-path: /hub
spring:
  profiles:
    active: developer
  #    active: operation
  #    active: test
  application:
    name: hub-service # current service name used for eureka registration

  devtools:
    add-properties: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


#---- eureka public config
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 20 # Notifying Eureka that the client is up or down or killed (second)
    leaseExpirationDurationInSeconds: 20 # Notifying Eureka that the client is up or down or killed (second)
    prefer-ip-address: true # registers the service ip rather than the server name
  client:
    register-with-eureka: true # register him self at eureka
    fetch-registry: true # pull down a local copy of the registries
#----------- allowed cors origin
cors:
  allowed-origins:
    - http://91.107.191.99:8090
    - http://91.107.191.99:8092
    - http://127.0.0.1:8090
    - http://127.0.0.1:8092
