spring:
  application:
    name: gateway-service # gateway service name to be called by it clients
  profiles:
    active: developer # default profile
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-origins: "http://localhost:3000,http://localhost:3001,http://172.24.66.76:8082,http://172.24.66.76:8086"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true

      discovery:
        locator:
          enabled: true # use netflix eureka discovery service
          #lower-case-service-id: true # debug in camelCase service name
      routes:
        - id: authentication-service
          uri: lb://authentication-service # netflix eureka correspondent service
          predicates:
            - Path=/authentication/** # how we will map the url to the target service
        #----------------------------------------
        - id: hub-service
          uri: lb://hub-service # netflix eureka correspondent service
          predicates:
            - Path=/hub/** # how we will map the url to the target service
        #----------------------------------------

  #cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=*
  #spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,OPTIONS
  #spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    configUrl: ${server.servlet.contextPath}/v3/api-docs/swagger-config
    url: ${server.servlet.contextPath}/v3/api-docs
    urls:
      - name: authentication
        url: /authentication/v3/api-docs
      - name: hub
        url: /hub/v3/api-docs
